### ISSUE TITLE
Schema Checklist

### ISSUE THREAD

**Issue by iProgYou** [k99909/MeTube#2]
# Database Schema
- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
  - [x] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are lowercased, snake_cased and `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`
## Comments

**Comment by iProgYou** [comment]
- firstname, lastname are probably unneccesary
- refrain from profile picture at first. You can add that in later
- It appears as though you will be using likes in both comments and videos. This is what is called a polymorphic association. You will want to research this before you implement that table
- You likely don't need views to be a separate table, but we can chat about this

**Comment by k99909** [comment]
Just completed these
