### ISSUE TITLE
Frontend routes

### ISSUE THREAD

**Issue by k99909** [k99909/MeTube#5]
# Frontend Routes
- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)
## Comments

**Comment by iProgYou** [comment]
- Detail the index page a bit. It is a big part of your videos MVP
- `/videos/:videoId/:commentId/:edit` what is this for? Won't the comment form be on the video show page?
